spring.application.name=API

# ====== #
# ANA Configuration
# ====== #

ana.username=${ANA_USERNAME}
ana.password=${ANA_PASSWORD}

ana.endpoints.auth=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/OAUth/v1
ana.endpoints.uf=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroUF/v1
ana.endpoints.bacias=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroBacia/v1
ana.endpoints.sub-bacias=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroSubBacia/v1
ana.endpoints.municipios=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroMunicipio/v1
ana.endpoints.estacoes=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroInventarioEstacoes/v1
ana.endpoints.serie-vazao=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroSerieVazao/v1
ana.endpoints.serie-chuva=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroSerieChuva/v1
ana.endpoints.serie-nivel=https://www.ana.gov.br/hidrowebservice/EstacoesTelemetricas/HidroinfoanaSerieTelemetricaAdotada/v1

# ====== #
# Open-Meteo Configuration
# ====== #
open-meteo.endpoints.geocoding=https://geocoding-api.open-meteo.com/v1/search
open-meteo.endpoints.flood=https://flood-api.open-meteo.com/v1/flood
open-meteo.endpoints.historicalWeather=https://archive-api.open-meteo.com/v1/archive
